name: Enviar reporte por correo

on:
  push:
    branches:
      - DEV

jobs:
  enviar-reporte:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Enviar correo con reporte
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: '📊 Reporte HTML generado automáticamente'
          to: raynieradames@gmail.com
          from: ${{ secrets.EMAIL_USER }}
          body: |
            Hola,

            Se adjunta el reporte HTML generado en la rama DEV.

            Saludos.
          attachments: reports/report_drif.html
